<?php

namespace ContainerDStwQwx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRegistrationRestControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Rest\RegistrationRestController' shared autowired service.
     *
     * @return \App\Controller\Rest\RegistrationRestController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Rest/RegistrationRestController.php';

        $container->services['App\\Controller\\Rest\\RegistrationRestController'] = $instance = new \App\Controller\Rest\RegistrationRestController(($container->privates['security.user_password_hasher'] ?? $container->load('getSecurity_UserPasswordHasherService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\Rest\\RegistrationRestController', $container));

        return $instance;
    }
}
