<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDC9lt0f\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDC9lt0f/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDC9lt0f.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDC9lt0f\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDC9lt0f\App_KernelDevDebugContainer([
    'container.build_hash' => 'DC9lt0f',
    'container.build_id' => '62840b9a',
    'container.build_time' => 1746042485,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDC9lt0f');
